spring:
    datasource:
        url: jdbc:postgresql://db:5432/michelet_db
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka/
