name: CI-PROD

on:
    pull_request:
        branches: [ main, dev ]
    push:
        branches: [ main, dev ]

permissions:
    contents: read # 내 코드를 읽을 수 있게(코드이동) 접근 권한을 준다.
    id-token: write # OIDC 토큰을 발급할 수 있게 한다.

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout # 내 코드 이동 깃허브 컴퓨터로
                uses: actions/checkout@v4

            -   name: Set up JDK 17  # jdk 환경 설치
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: "17"

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Grant execute permission for gradlew
                run: chmod +x ./gradlew

            -   name: Run tests # 테스트 실행
                run: ./gradlew test --no-daemon

            -   name: Generate image tag
                run: echo "IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

            -   name: Configure AWS credentials (OIDC) # OIDC 기반으로 역할 자격증명
                if: github.event_name == 'push'
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                    aws-region: ${{ vars.AWS_REGION }}

            -   name: Login to Amazon ECR # 위에서 자격증명하고 ecr 로그인
                if: github.event_name == 'push'
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Build Docker image  # 이미지 빌드해서
                run: |
                    docker build --build-arg SERVER_PORT=${{ vars.SERVER_PORT }} -t ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

            -   name: Push Docker image to ECR # 이미지 ecr로 업로드
                if: github.event_name == 'push'
                run: |
                    docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
